version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/doublecheck/static
      - media-data:/doublecheck/media

  proxy:
    build:
      context: ./proxy
    restart: always
    volumes:
      - static-data:/doublecheck/static
      - media-data:/doublecheck/media
    ports:
      - 8000:8000
    depends_on:
      - app

volumes:
  static-data:
  media-data: